/************************************************************************************
 * File Name   		: ExceptionClass_test
 * Author	  		: ugon96@gmail.com
 * Date				: 2023-12-26
 * @Group              : Daeunextier 
 * Description 		: 
 * Modification Log
 * Ver       Date            Author      		    Modification
 * 1.0     2023-12-26       ugon96@gmail.com         Initial Version
*************************************************************************************/

@IsTest
private class ExceptionClass_test {
    @IsTest
    static void testBehavior() {
        ExceptionClass.testExtendedException();
    }
}