/************************************************************************************
 * File Name   		: LogWrapper_test
 * Author	  		: ugon96@gmail.com
 * Date				: 2023-10-20
 * @Group              : Daeunextier 
 * Description 		: 
 * Modification Log
 * Ver       Date            Author      		    Modification
 * 1.0     2023-10-20       ugon96@gmail.com         Initial Version
*************************************************************************************/

@IsTest
private class LogWrapper_test {
    @IsTest
    static void testBehavior() {
        LogWrapper objLogWrapper = new LogWrapper();
    }
}