/************************************************************************************
 * File Name   		: NewProductOrderController
 * Author	  		: ugon96@gmail.com
 * Date				: 2023-10-26
 * @Group              : Daeunextier 
 * Description 		: 
 * Modification Log
 * Ver       Date            Author      		    Modification
 * 1.0     2023-10-26       ugon96@gmail.com         Initial Version
*************************************************************************************/

public with sharing class NewProductOrderController {

}