/************************************************************************************
 * File Name   		: TYM_ProductsOrderCloneController
 * Author	  		: ugon96@gmail.com
 * Date				: 2023-12-08
 * @Group              : Daeunextier 
 * Description 		: 
 * Modification Log
 * Ver       Date            Author      		    Modification
 * 1.0     2023-12-08       ugon96@gmail.com         Initial Version
*************************************************************************************/

public with sharing class TYM_ProductsOrderCloneController {
    @AuraEnabled
    public static String productsOrderClone(String recordId, Map<String, String> partsOrderMap) {
        String result = '';
        return result;
    }
}